### ISSUE TITLE
Spinner stops animating when page goes out 

### ISSUE THREAD

**Issue by kunalverma25** [devnikor/Spinner#2]

**Comment by devnikor** [comment]
Hello! Can you please provide some description about this issue?

**Comment by kunalverma25** [comment]
I have a tab bar based application.
I am loading data in background.
If a spinner is showing in one tab.. and user navigates away and comes back. the spinner does not animate. and is stuck until background operation completes and spinner is hidden.

**Comment by devnikor** [comment]
OK, thanks! I'll look at this as soon as possible

**Comment by kunalverma25** [comment]
Thanks, I managed to solve it though..
For anyone else having this issue..
Just do this in your ViewController.swif

override func viewWillAppear(animated: Bool) {
        spinner.indicator.beginAnimation()
    }
