### ISSUE TITLE
Is there any way to change the color of the spinner?

### ISSUE THREAD

**Issue by Edig** [devnikor/Spinner#3]
Is there any way to change the color of the spinner?

**Comment by devnikor** [comment]
Hello!
Right now you can use something like this (if you don't changed default activity indicator):
```(spinner.indicator.indicatorView as? CircleIndicator)?.lineColor = UIColor.blackColor()```

**Comment by devnikor** [comment]
I'll move color settings to ```SpinnerConfiguration``` in next release

**Comment by Edig** [comment]
Thanks :D.
